services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: vacation_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      postgres 
      -c shared_preload_libraries='pg_cron' 
      -c cron.database_name='${POSTGRES_DB}'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: vacation_redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    user: root
    restart: always
    env_file:
      - .env 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        echo "vacation_db:5432:$${POSTGRES_DB}:$${POSTGRES_USER}:$${POSTGRES_PASSWORD}" > /tmp/pgpassfile
        chmod 600 /tmp/pgpassfile
        chown 5050:5050 /tmp/pgpassfile
        
        cat <<EOF > /pgadmin4/servers.json
        {
            "Servers": {
                "1": {
                    "Name": "VacationAgent DB",
                    "Group": "Servers",
                    "Host": "vacation_db",
                    "Port": 5432,
                    "MaintenanceDB": "$${POSTGRES_DB}",
                    "Username": "$${POSTGRES_USER}",
                    "SSLMode": "prefer",
                    "PassFile": "/tmp/pgpassfile"
                }
            }
        }
        EOF
        chown 5050:5050 /pgadmin4/servers.json
        
        /entrypoint.sh
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data: