"""new attractions table

Revision ID: 02ea6d591188
Revises: b6597b698728
Create Date: 2026-05-06 12:12:08.786143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02ea6d591188'
down_revision: Union[str, Sequence[str], None] = 'b6597b698728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_place_id', sa.String(), nullable=True),
    sa.Column('wikidata_id', sa.String(), nullable=True),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_tier', sa.Integer(), nullable=True),
    sa.Column('recommended_duration_mins', sa.Integer(), nullable=True),
    sa.Column('tod_preference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_attractions_category'), 'global_attractions', ['category'], unique=False)
    op.create_index(op.f('ix_global_attractions_city'), 'global_attractions', ['city'], unique=False)
    op.create_index(op.f('ix_global_attractions_country'), 'global_attractions', ['country'], unique=False)
    op.create_index(op.f('ix_global_attractions_external_place_id'), 'global_attractions', ['external_place_id'], unique=True)
    op.create_index(op.f('ix_global_attractions_id'), 'global_attractions', ['id'], unique=False)
    op.create_index(op.f('ix_global_attractions_official_name'), 'global_attractions', ['official_name'], unique=False)
    op.create_index(op.f('ix_global_attractions_state_province'), 'global_attractions', ['state_province'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_attractions_state_province'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_official_name'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_id'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_external_place_id'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_country'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_city'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_category'), table_name='global_attractions')
    op.drop_table('global_attractions')
    # ### end Alembic commands ###
