"""add transit strategy column

Revision ID: 052f7eb1443f
Revises: 8e27d790786e
Create Date: 2026-04-28 20:41:02.816861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '052f7eb1443f'
down_revision: Union[str, Sequence[str], None] = '8e27d790786e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('transit_strategy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_sessions', 'transit_strategy')
    # ### end Alembic commands ###
