"""added budget to session

Revision ID: 1e6e388c9646
Revises: 736bec108885
Create Date: 2026-03-18 14:15:34.282937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e6e388c9646'
down_revision: Union[str, Sequence[str], None] = '736bec108885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('flight_price', sa.Float(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('accomodation_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_sessions', 'accomodation_price')
    op.drop_column('vacation_sessions', 'flight_price')
    op.drop_column('vacation_sessions', 'budget')
    # ### end Alembic commands ###
