"""add traveler details to vacation session

Revision ID: 3d68f378e675
Revises: 1a8d75eda87a
Create Date: 2026-03-02 00:02:34.535168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d68f378e675'
down_revision: Union[str, Sequence[str], None] = '1a8d75eda87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('adults', sa.Integer(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('children', sa.Integer(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('infants_in_seat', sa.Integer(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('infants_on_lap', sa.Integer(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('children_ages', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_sessions', 'children_ages')
    op.drop_column('vacation_sessions', 'infants_on_lap')
    op.drop_column('vacation_sessions', 'infants_in_seat')
    op.drop_column('vacation_sessions', 'children')
    op.drop_column('vacation_sessions', 'adults')
    # ### end Alembic commands ###
