"""added itinerary text and extra links to session

Revision ID: 56b9607b3e7b
Revises: 6f35ea4cce0c
Create Date: 2026-04-03 12:05:32.165861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b9607b3e7b'
down_revision: Union[str, Sequence[str], None] = '6f35ea4cce0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('itinerary_text', sa.Text(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('extra_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_sessions', 'extra_links')
    op.drop_column('vacation_sessions', 'itinerary_text')
    # ### end Alembic commands ###
