"""create_vacation_companions_bridge

Revision ID: 736bec108885
Revises: 3fdf81ff6cfe
Create Date: 2026-03-11 16:58:48.891523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736bec108885'
down_revision: Union[str, Sequence[str], None] = '3fdf81ff6cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_companions',
    sa.Column('vacation_session_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['travel_companions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacation_session_id'], ['vacation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacation_session_id', 'companion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation_companions')
    # ### end Alembic commands ###
