"""initial migration

Revision ID: 818f6ae5af85
Revises: 
Create Date: 2026-05-28 12:39:58.403862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818f6ae5af85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_blacklist_tokens_token'), 'blacklist_tokens', ['token'], unique=False)
    op.create_table('global_attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_place_id', sa.String(), nullable=True),
    sa.Column('wikidata_id', sa.String(), nullable=True),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_tier', sa.Integer(), nullable=True),
    sa.Column('recommended_duration_mins', sa.Integer(), nullable=True),
    sa.Column('tod_preference', sa.String(), nullable=True),
    sa.Column('needs_reservation', sa.Boolean(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('must_count', sa.Integer(), nullable=False),
    sa.Column('want_count', sa.Integer(), nullable=False),
    sa.Column('optional_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_attractions_category'), 'global_attractions', ['category'], unique=False)
    op.create_index(op.f('ix_global_attractions_city'), 'global_attractions', ['city'], unique=False)
    op.create_index(op.f('ix_global_attractions_country'), 'global_attractions', ['country'], unique=False)
    op.create_index(op.f('ix_global_attractions_external_place_id'), 'global_attractions', ['external_place_id'], unique=True)
    op.create_index(op.f('ix_global_attractions_id'), 'global_attractions', ['id'], unique=False)
    op.create_index(op.f('ix_global_attractions_official_name'), 'global_attractions', ['official_name'], unique=False)
    op.create_index(op.f('ix_global_attractions_state_province'), 'global_attractions', ['state_province'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('user_description', sa.String(), nullable=True),
    sa.Column('currency_preference', sa.String(), nullable=True),
    sa.Column('home_airports', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('travel_companions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_infant_on_lap', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_companions_id'), 'travel_companions', ['id'], unique=False)
    op.create_table('vacation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_stage', sa.Enum('DISCOVERY', 'OPTIONS', 'ITINERARY', 'BOOKING', 'COMPLETED', name='sessionstage'), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('departure', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('infants_in_seat', sa.Integer(), nullable=True),
    sa.Column('infants_on_lap', sa.Integer(), nullable=True),
    sa.Column('children_ages', sa.String(), nullable=True),
    sa.Column('room_qty', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('destination_arrival', sa.DateTime(), nullable=True),
    sa.Column('destination_departure', sa.DateTime(), nullable=True),
    sa.Column('flights_url', sa.Text(), nullable=True),
    sa.Column('flight_price', sa.Float(), nullable=True),
    sa.Column('flight_ccy', sa.String(), nullable=True),
    sa.Column('airport_latitude', sa.Float(), nullable=True),
    sa.Column('airport_longitude', sa.Float(), nullable=True),
    sa.Column('airport_name', sa.String(), nullable=True),
    sa.Column('accommodation_url', sa.Text(), nullable=True),
    sa.Column('accommodation_price', sa.Float(), nullable=True),
    sa.Column('accommodation_ccy', sa.String(), nullable=True),
    sa.Column('accommodation_latitude', sa.Float(), nullable=True),
    sa.Column('accommodation_longitude', sa.Float(), nullable=True),
    sa.Column('accommodation_address', sa.String(), nullable=True),
    sa.Column('accommodation_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_sessions_id'), 'vacation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_vacation_sessions_user_id'), 'vacation_sessions', ['user_id'], unique=False)
    op.create_table('vacations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('flights_url', sa.Text(), nullable=True),
    sa.Column('flight_price', sa.Float(), nullable=True),
    sa.Column('flight_ccy', sa.String(), nullable=True),
    sa.Column('airport_name', sa.String(), nullable=True),
    sa.Column('accommodation_url', sa.Text(), nullable=True),
    sa.Column('accommodation_price', sa.Float(), nullable=True),
    sa.Column('accommodation_ccy', sa.String(), nullable=True),
    sa.Column('accommodation_name', sa.String(), nullable=True),
    sa.Column('accommodation_address', sa.String(), nullable=True),
    sa.Column('itinerary_data', sa.JSON(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_vacations_id'), 'vacations', ['id'], unique=False)
    op.create_index(op.f('ix_vacations_is_finalized'), 'vacations', ['is_finalized'], unique=False)
    op.create_table('vacation_companions',
    sa.Column('vacation_session_id', sa.Integer(), nullable=False),
    sa.Column('companion_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['companion_id'], ['travel_companions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacation_session_id'], ['vacation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacation_session_id', 'companion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation_companions')
    op.drop_index(op.f('ix_vacations_is_finalized'), table_name='vacations')
    op.drop_index(op.f('ix_vacations_id'), table_name='vacations')
    op.drop_table('vacations')
    op.drop_index(op.f('ix_vacation_sessions_user_id'), table_name='vacation_sessions')
    op.drop_index(op.f('ix_vacation_sessions_id'), table_name='vacation_sessions')
    op.drop_table('vacation_sessions')
    op.drop_index(op.f('ix_travel_companions_id'), table_name='travel_companions')
    op.drop_table('travel_companions')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_global_attractions_state_province'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_official_name'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_id'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_external_place_id'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_country'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_city'), table_name='global_attractions')
    op.drop_index(op.f('ix_global_attractions_category'), table_name='global_attractions')
    op.drop_table('global_attractions')
    op.drop_index(op.f('ix_blacklist_tokens_token'), table_name='blacklist_tokens')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
