"""changed itinerary data struructure

Revision ID: 8e27d790786e
Revises: 3a679a51e891
Create Date: 2026-04-27 20:23:19.565325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e27d790786e'
down_revision: Union[str, Sequence[str], None] = '3a679a51e891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('itinerary_data', sa.JSON(), nullable=True))
    op.drop_column('vacation_sessions', 'extra_links')
    op.drop_column('vacation_sessions', 'itinerary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('itinerary_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vacation_sessions', sa.Column('extra_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('vacation_sessions', 'itinerary_data')
    # ### end Alembic commands ###
