"""added attractions fields for ranking

Revision ID: 9ec023287533
Revises: b8ef1bee3eed
Create Date: 2026-05-26 16:02:40.017926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ec023287533'
down_revision: Union[str, Sequence[str], None] = 'b8ef1bee3eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_attractions', sa.Column('needs_reservation', sa.Boolean(), nullable=True))
    op.add_column('global_attractions', sa.Column('search_count', sa.Integer(), nullable=False))
    op.add_column('global_attractions', sa.Column('must_count', sa.Integer(), nullable=False))
    op.add_column('global_attractions', sa.Column('want_count', sa.Integer(), nullable=False))
    op.add_column('global_attractions', sa.Column('optional_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_attractions', 'optional_count')
    op.drop_column('global_attractions', 'want_count')
    op.drop_column('global_attractions', 'must_count')
    op.drop_column('global_attractions', 'search_count')
    op.drop_column('global_attractions', 'needs_reservation')
    # ### end Alembic commands ###
