"""added model for the history

Revision ID: b6597b698728
Revises: 052f7eb1443f
Create Date: 2026-04-29 14:28:25.355817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6597b698728'
down_revision: Union[str, Sequence[str], None] = '052f7eb1443f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('flight_ccy', sa.String(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('accomodation_ccy', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('vacations', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('from_date', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('to_date', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('people_count', sa.Integer(), nullable=True))
    op.add_column('vacations', sa.Column('flight_price', sa.Float(), nullable=True))
    op.add_column('vacations', sa.Column('flight_ccy', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('accomodation_price', sa.Float(), nullable=True))
    op.add_column('vacations', sa.Column('accomodation_ccy', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('itinerary_data', sa.JSON(), nullable=True))
    op.add_column('vacations', sa.Column('transit_strategy', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'vacations', ['session_id'])
    op.drop_column('vacations', 'flights')
    op.drop_column('vacations', 'end_date')
    op.drop_column('vacations', 'currency')
    op.drop_column('vacations', 'itinerary')
    op.drop_column('vacations', 'departure')
    op.drop_column('vacations', 'description')
    op.drop_column('vacations', 'start_date')
    op.drop_column('vacations', 'total_price')
    op.drop_column('vacations', 'updated_at')
    op.drop_column('vacations', 'hotels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('hotels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('vacations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('departure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vacations', sa.Column('itinerary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('vacations', sa.Column('flights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vacations', type_='unique')
    op.drop_column('vacations', 'transit_strategy')
    op.drop_column('vacations', 'itinerary_data')
    op.drop_column('vacations', 'accomodation_ccy')
    op.drop_column('vacations', 'accomodation_price')
    op.drop_column('vacations', 'flight_ccy')
    op.drop_column('vacations', 'flight_price')
    op.drop_column('vacations', 'people_count')
    op.drop_column('vacations', 'to_date')
    op.drop_column('vacations', 'from_date')
    op.drop_column('vacations', 'origin')
    op.drop_column('vacations', 'session_id')
    op.drop_column('vacation_sessions', 'accomodation_ccy')
    op.drop_column('vacation_sessions', 'flight_ccy')
    # ### end Alembic commands ###
