"""added airport and hotel coordinates

Revision ID: b8ef1bee3eed
Revises: d1a627a10c5f
Create Date: 2026-05-11 23:53:10.111982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8ef1bee3eed'
down_revision: Union[str, Sequence[str], None] = 'd1a627a10c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('airport_latitude', sa.Float(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('airport_longitude', sa.Float(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('airport_name', sa.String(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('accommodation_latitude', sa.Float(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('accommodation_longitude', sa.Float(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('accommodation_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_sessions', 'accommodation_address')
    op.drop_column('vacation_sessions', 'accommodation_longitude')
    op.drop_column('vacation_sessions', 'accommodation_latitude')
    op.drop_column('vacation_sessions', 'airport_name')
    op.drop_column('vacation_sessions', 'airport_longitude')
    op.drop_column('vacation_sessions', 'airport_latitude')
    # ### end Alembic commands ###
