"""add time info for itinerary

Revision ID: b9c64304b69e
Revises: 56b9607b3e7b
Create Date: 2026-04-09 18:02:39.310869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9c64304b69e'
down_revision: Union[str, Sequence[str], None] = '56b9607b3e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('destination_arrival', sa.DateTime(), nullable=True))
    op.add_column('vacation_sessions', sa.Column('destination_departure', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_sessions', 'destination_departure')
    op.drop_column('vacation_sessions', 'destination_arrival')
    # ### end Alembic commands ###
