"""added opening hours

Revision ID: d1a627a10c5f
Revises: 02ea6d591188
Create Date: 2026-05-11 22:16:04.753389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1a627a10c5f'
down_revision: Union[str, Sequence[str], None] = '02ea6d591188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_attractions', sa.Column('opening_hours', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_attractions', 'opening_hours')
    # ### end Alembic commands ###
