"""update vacation data

Revision ID: da6889f9338b
Revises: 9ec023287533
Create Date: 2026-05-27 14:08:38.569879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da6889f9338b'
down_revision: Union[str, Sequence[str], None] = '9ec023287533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_sessions', sa.Column('accommodation_name', sa.String(), nullable=True))
    op.drop_column('vacation_sessions', 'itinerary_data')
    op.drop_column('vacation_sessions', 'transit_strategy')
    op.add_column('vacations', sa.Column('adults', sa.Integer(), nullable=False))
    op.add_column('vacations', sa.Column('children', sa.Integer(), nullable=False))
    op.add_column('vacations', sa.Column('flights_url', sa.Text(), nullable=True))
    op.add_column('vacations', sa.Column('airport_name', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('accomodation_url', sa.Text(), nullable=True))
    op.add_column('vacations', sa.Column('accomodation_name', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('accomodation_address', sa.String(), nullable=True))
    op.add_column('vacations', sa.Column('is_finalized', sa.Boolean(), nullable=False))
    op.alter_column('vacations', 'from_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=False),
               existing_nullable=True,
               postgresql_using="from_date::timestamp without time zone")
    op.alter_column('vacations', 'to_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=False),
               existing_nullable=True,
               postgresql_using="to_date::timestamp without time zone")
    op.create_index(op.f('ix_vacations_is_finalized'), 'vacations', ['is_finalized'], unique=False)
    op.drop_column('vacations', 'people_count')
    op.drop_column('vacations', 'transit_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('transit_strategy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('vacations', sa.Column('people_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vacations_is_finalized'), table_name='vacations')
    op.alter_column(
        'vacations',
        'to_date',
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="to_date::text",
    )

    op.alter_column(
        'vacations',
        'from_date',
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="from_date::text",
    )
    op.drop_column('vacations', 'is_finalized')
    op.drop_column('vacations', 'accomodation_address')
    op.drop_column('vacations', 'accomodation_name')
    op.drop_column('vacations', 'accomodation_url')
    op.drop_column('vacations', 'airport_name')
    op.drop_column('vacations', 'flights_url')
    op.drop_column('vacations', 'children')
    op.drop_column('vacations', 'adults')
    op.add_column('vacation_sessions', sa.Column('transit_strategy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('vacation_sessions', sa.Column('itinerary_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('vacation_sessions', 'accommodation_name')
    